'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Filmmaker.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _64Clockwork() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_64Clockwork", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _64networklogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_64networklogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property About() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("About", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Build Date: .
        '''</summary>
        Friend ReadOnly Property AboutBuildDate() As String
            Get
                Return ResourceManager.GetString("AboutBuildDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Created by James &quot;CaptainSwag101&quot; Pelster.
        '''</summary>
        Friend ReadOnly Property AboutCreatorDesc() As String
            Get
                Return ResourceManager.GetString("AboutCreatorDesc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Help.
        '''</summary>
        Friend ReadOnly Property AboutMenu() As String
            Get
                Return ResourceManager.GetString("AboutMenu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to About Advanced Cinematic Control....
        '''</summary>
        Friend ReadOnly Property AboutStrip() As String
            Get
                Return ResourceManager.GetString("AboutStrip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This program is dedicated to the Super Mario 64 Bloopers/Machinima community, thanks for all the effort you&apos;ve put into your work, and I hope this tool will help you create awesome videos for years to come!.
        '''</summary>
        Friend ReadOnly Property AboutText1() As String
            Get
                Return ResourceManager.GetString("AboutText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Special thanks to Matthew &quot;MATTHEWGU4&quot; Guerra for helping me make this project a reality and for spreading the word, and to GlitchyPSIX for his discovery of the &quot;Soft-Freeze&quot; feature..
        '''</summary>
        Friend ReadOnly Property AboutText2() As String
            Get
                Return ResourceManager.GetString("AboutText2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Found any bugs, need help, or want to suggest a feature? Email me at:.
        '''</summary>
        Friend ReadOnly Property AboutText3() As String
            Get
                Return ResourceManager.GetString("AboutText3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ACC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ACC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ACC1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ACC1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ADD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ADD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Addon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Addon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Animation data not loaded!.
        '''</summary>
        Friend ReadOnly Property AnimationDataNotLoaded() As String
            Get
                Return ResourceManager.GetString("AnimationDataNotLoaded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error reading animation data file:.
        '''</summary>
        Friend ReadOnly Property AnimationDataReadError() As String
            Get
                Return ResourceManager.GetString("AnimationDataReadError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Animation Swap Control.
        '''</summary>
        Friend ReadOnly Property AnimationGroupName() As String
            Get
                Return ResourceManager.GetString("AnimationGroupName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Overwrite this animation....
        '''</summary>
        Friend ReadOnly Property AnimationO1() As String
            Get
                Return ResourceManager.GetString("AnimationO1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ...with this one!.
        '''</summary>
        Friend ReadOnly Property AnimationO2() As String
            Get
                Return ResourceManager.GetString("AnimationO2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Background2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Background2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Background3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Background3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Background4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Background4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Background5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Background5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Background6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Background6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Background7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Background7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Background8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Background8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The base address is: .
        '''</summary>
        Friend ReadOnly Property BaseAddressIs() As String
            Get
                Return ResourceManager.GetString("BaseAddressIs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Base address not found!.
        '''</summary>
        Friend ReadOnly Property BaseAddressNotFound() As String
            Get
                Return ResourceManager.GetString("BaseAddressNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You are attempting to write to the first four bytes of Super Mario 64&apos;s memory, which contains the value this program uses to find the game&apos;s base address. If you click &quot;&quot;Yes&quot;&quot;, you will need to reset the emulator before this program will be able to find Super Mario 64 again. Are you sure you want to do this?.
        '''</summary>
        Friend ReadOnly Property BaseAddressOverwriteWarning() As String
            Get
                Return ResourceManager.GetString("BaseAddressOverwriteWarning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bugged() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bugged", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Normal Camera Controls.
        '''</summary>
        Friend ReadOnly Property CamControlName() As String
            Get
                Return ResourceManager.GetString("CamControlName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Camera position locked. Click the button below to lock camera rotation..
        '''</summary>
        Friend ReadOnly Property CameraLockDesc() As String
            Get
                Return ResourceManager.GetString("CameraLockDesc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Camera rotation unlocked. Click the button below to lock camera rotation..
        '''</summary>
        Friend ReadOnly Property CameraUnlockDesc() As String
            Get
                Return ResourceManager.GetString("CameraUnlockDesc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Want to set these colors as default?.
        '''</summary>
        Friend ReadOnly Property CCSDefaultMB() As String
            Get
                Return ResourceManager.GetString("CCSDefaultMB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Defaults.
        '''</summary>
        Friend ReadOnly Property CCSDefaults() As String
            Get
                Return ResourceManager.GetString("CCSDefaults", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Set as default?.
        '''</summary>
        Friend ReadOnly Property CCSDMBTitle() As String
            Get
                Return ResourceManager.GetString("CCSDMBTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Close.
        '''</summary>
        Friend ReadOnly Property CCSEXbtn() As String
            Get
                Return ResourceManager.GetString("CCSEXbtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel.
        '''</summary>
        Friend ReadOnly Property CCSEXCancel() As String
            Get
                Return ResourceManager.GetString("CCSEXCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Here&apos;s that color code you asked for!.
        '''</summary>
        Friend ReadOnly Property CCSEXLabel() As String
            Get
                Return ResourceManager.GetString("CCSEXLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Export color code....
        '''</summary>
        Friend ReadOnly Property CCSExport() As String
            Get
                Return ResourceManager.GetString("CCSExport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Color Code Studio.
        '''</summary>
        Friend ReadOnly Property CCSFormTitle() As String
            Get
                Return ResourceManager.GetString("CCSFormTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gloves.
        '''</summary>
        Friend ReadOnly Property CCSGloves() As String
            Get
                Return ResourceManager.GetString("CCSGloves", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hair.
        '''</summary>
        Friend ReadOnly Property CCSHair() As String
            Get
                Return ResourceManager.GetString("CCSHair", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hat/Shirt.
        '''</summary>
        Friend ReadOnly Property CCSHat() As String
            Get
                Return ResourceManager.GetString("CCSHat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Paste your color code into the textbox below, then click &quot;OK&quot;..
        '''</summary>
        Friend ReadOnly Property CCSIMLabel() As String
            Get
                Return ResourceManager.GetString("CCSIMLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Import color code....
        '''</summary>
        Friend ReadOnly Property CCSImport() As String
            Get
                Return ResourceManager.GetString("CCSImport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error occurred while trying to import the color code. Make sure you entered a valid code!.
        '''</summary>
        Friend ReadOnly Property CCSImportError() As String
            Get
                Return ResourceManager.GetString("CCSImportError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Load from game.
        '''</summary>
        Friend ReadOnly Property CCSLoad() As String
            Get
                Return ResourceManager.GetString("CCSLoad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Overalls.
        '''</summary>
        Friend ReadOnly Property CCSOveralls() As String
            Get
                Return ResourceManager.GetString("CCSOveralls", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Shoes.
        '''</summary>
        Friend ReadOnly Property CCSShoes() As String
            Get
                Return ResourceManager.GetString("CCSShoes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Skin.
        '''</summary>
        Friend ReadOnly Property CCSSkin() As String
            Get
                Return ResourceManager.GetString("CCSSkin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IMPORTANT: Make sure to uncheck any color codes currently enabled in Project64. Otherwise, they will prevent this program from modifying Mario&apos;s colors..
        '''</summary>
        Friend ReadOnly Property CCWarning() As String
            Get
                Return ResourceManager.GetString("CCWarning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Change Camera Type.
        '''</summary>
        Friend ReadOnly Property ChangeCameraType() As String
            Get
                Return ResourceManager.GetString("ChangeCameraType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CHK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CHK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CHT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CHT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Connected() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Connected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Crit() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Crit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Critical() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Critical", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Death() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Death", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property DeepFreeze() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("DeepFreeze", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DELADD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DELADD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Disconnect() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Disconnect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Exception() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Exception", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Expand() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Expand", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Explode() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Explode", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Explosion() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Explosion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Extras() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Extras", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EYE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EYE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Flying() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Flying", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Force Camera to be movable with C-Buttons.
        '''</summary>
        Friend ReadOnly Property ForceCameraC() As String
            Get
                Return ResourceManager.GetString("ForceCameraC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Click this whenever you are in an area that does not allow
        '''the camera to be rotated with the C-buttons (such as the
        '''inside of the castle) and the camera will be temporarily allowed
        '''to be manually rotated in the usual manner. However, this
        '''does not always work in all areas of the castle, as sometimes
        '''camera behaviors are hardcoded into specific parts of levels..
        '''</summary>
        Friend ReadOnly Property ForceCameraCTooltip() As String
            Get
                Return ResourceManager.GetString("ForceCameraCTooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FR4PS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR4PS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Freeze Camera.
        '''</summary>
        Friend ReadOnly Property FreezeCamera() As String
            Get
                Return ResourceManager.GetString("FreezeCamera", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property froze() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("froze", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Frozen() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Frozen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property GiveCrit() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("GiveCrit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Glitch() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Glitch", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Gotcha() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Gotcha", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Go to new area.
        '''</summary>
        Friend ReadOnly Property GotoNewArea() As String
            Get
                Return ResourceManager.GetString("GotoNewArea", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Guides() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Guides", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Hang() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hang", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Help....
        '''</summary>
        Friend ReadOnly Property HelpStrip() As String
            Get
                Return ResourceManager.GetString("HelpStrip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property HighScore() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("HighScore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Hit() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Hit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Hold() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hold", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hover Control.
        '''</summary>
        Friend ReadOnly Property HoverControlName() As String
            Get
                Return ResourceManager.GetString("HoverControlName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 5 (Highest).
        '''</summary>
        Friend ReadOnly Property HoverMax() As String
            Get
                Return ResourceManager.GetString("HoverMax", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 0 (None).
        '''</summary>
        Friend ReadOnly Property HoverMin() As String
            Get
                Return ResourceManager.GetString("HoverMin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reminder: Some animations won&apos;t be affected by this. Recommended value is 1..
        '''</summary>
        Friend ReadOnly Property HoverToolTip() As String
            Get
                Return ResourceManager.GetString("HoverToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Idea() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Idea", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Injector2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Injector2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The value you have entered is not a valid Hexadecimal address..
        '''</summary>
        Friend ReadOnly Property InvalidHexAddress() As String
            Get
                Return ResourceManager.GetString("InvalidHexAddress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The number you have entered is not a valid Hexadecimal value..
        '''</summary>
        Friend ReadOnly Property InvalidHexValue() As String
            Get
                Return ResourceManager.GetString("InvalidHexValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Address:.
        '''</summary>
        Friend ReadOnly Property IOAddr() As String
            Get
                Return ResourceManager.GetString("IOAddr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I know what I&apos;m doing..
        '''</summary>
        Friend ReadOnly Property IOBadass() As String
            Get
                Return ResourceManager.GetString("IOBadass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Memory I/O Editor.
        '''</summary>
        Friend ReadOnly Property IOFormTitle() As String
            Get
                Return ResourceManager.GetString("IOFormTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Memory Controls.
        '''</summary>
        Friend ReadOnly Property IOGroupName() As String
            Get
                Return ResourceManager.GetString("IOGroupName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Read.
        '''</summary>
        Friend ReadOnly Property IORead() As String
            Get
                Return ResourceManager.GetString("IORead", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Value:.
        '''</summary>
        Friend ReadOnly Property IOValue() As String
            Get
                Return ResourceManager.GetString("IOValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Write.
        '''</summary>
        Friend ReadOnly Property IOWrite() As String
            Get
                Return ResourceManager.GetString("IOWrite", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Jump() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Jump", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LIADD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LIADD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LoadAddon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LoadAddon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LoadCheatSht() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LoadCheatSht", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LOADD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LOADD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LoadingBalls() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LoadingBalls", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LoadSpecialPkg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LoadSpecialPkg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property M64MM2_CC_Mario_big() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("M64MM2_CC_Mario_big", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property M64MM2_Icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("M64MM2_Icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This window is for testing reading from/writing to SM64&apos;s memory (RAM). You should only use this if you know what you&apos;re doing. The developers accept no responsibility for lost save data, program crashes, or system crashes..
        '''</summary>
        Friend ReadOnly Property MemDebugWarning() As String
            Get
                Return ResourceManager.GetString("MemDebugWarning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Message() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MoveRoute() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MoveRoute", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Multipart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Multipart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property No() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("No", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You cannot turn on the Precision Mode because Project64 isn&apos;t open..
        '''</summary>
        Friend ReadOnly Property NoPJPrecisionError() As String
            Get
                Return ResourceManager.GetString("NoPJPrecisionError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Nudge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nudge", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Online() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Online", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OST() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OST", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PJ6A() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PJ6A", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Project64 isn&apos;t open!.
        '''</summary>
        Friend ReadOnly Property PJNotOpen() As String
            Get
                Return ResourceManager.GetString("PJNotOpen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Precision Mode is off..
        '''</summary>
        Friend ReadOnly Property PrecisionButtonDisabled() As String
            Get
                Return ResourceManager.GetString("PrecisionButtonDisabled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lock Camera Rotation.
        '''</summary>
        Friend ReadOnly Property PrecisionButtonLock() As String
            Get
                Return ResourceManager.GetString("PrecisionButtonLock", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unlock Camera Rotation.
        '''</summary>
        Friend ReadOnly Property PrecisionButtonUnlock() As String
            Get
                Return ResourceManager.GetString("PrecisionButtonUnlock", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Precision Camera Control.
        '''</summary>
        Friend ReadOnly Property PrecisionGroupName() As String
            Get
                Return ResourceManager.GetString("PrecisionGroupName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Precision Camera Control.
        '''</summary>
        Friend ReadOnly Property PrecisionModeBoxName() As String
            Get
                Return ResourceManager.GetString("PrecisionModeBoxName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Precision Mode.
        '''</summary>
        Friend ReadOnly Property PrecisionModeStrip() As String
            Get
                Return ResourceManager.GetString("PrecisionModeStrip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enables Precision Camera Mode, which lets you
        '''control the angle of the camera from Mario&apos;s first-person
        '''view and lock it wherever you want, and then readjust the camera at will..
        '''</summary>
        Friend ReadOnly Property PrecisionModeTooltip() As String
            Get
                Return ResourceManager.GetString("PrecisionModeTooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Precision Mode is disabled.
        '''Enable it in Settings -&gt; Precision Mode.
        '''</summary>
        Friend ReadOnly Property PrecisionStatusDisabled() As String
            Get
                Return ResourceManager.GetString("PrecisionStatusDisabled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Camera locked. Press the button below to re-adjust camera angle.
        '''To disable precision mode, uncheck Settings -&gt; Precision Mode.
        '''</summary>
        Friend ReadOnly Property PrecisionStatusFinish() As String
            Get
                Return ResourceManager.GetString("PrecisionStatusFinish", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Precision mode is disabled. Reason: Project64 isn&apos;t open..
        '''</summary>
        Friend ReadOnly Property PrecisionStatusNoEmu() As String
            Get
                Return ResourceManager.GetString("PrecisionStatusNoEmu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ProjectSF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ProjectSF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Punch() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Punch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Question() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Question", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Recorder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Recorder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remember previous animation swaps.
        '''</summary>
        Friend ReadOnly Property RememberPrevSwaps() As String
            Get
                Return ResourceManager.GetString("RememberPrevSwaps", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to When you select a new animation to be overwritten, any previous animations
        '''will remain swapped until you manually change or reset them..
        '''</summary>
        Friend ReadOnly Property RememberPrevSwapsTooltip() As String
            Get
                Return ResourceManager.GetString("RememberPrevSwapsTooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reset all animations to default (Malfunctioning).
        '''</summary>
        Friend ReadOnly Property ResetAllSwaps() As String
            Get
                Return ResourceManager.GetString("ResetAllSwaps", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This resets all animations to their original sequences.
        '''However, it currently does not work as intended, so
        '''I have disabled it until I determine how to fix it..
        '''</summary>
        Friend ReadOnly Property ResetAllSwapsTooltip() As String
            Get
                Return ResourceManager.GetString("ResetAllSwapsTooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Retract() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Retract", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Scanning for base address....
        '''</summary>
        Friend ReadOnly Property SearchingForBaseAddress() As String
            Get
                Return ResourceManager.GetString("SearchingForBaseAddress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Settings.
        '''</summary>
        Friend ReadOnly Property SettingsMenu() As String
            Get
                Return ResourceManager.GetString("SettingsMenu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SFX() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SFX", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SM64FM_Logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SM64FM_Logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Small Extras.
        '''</summary>
        Friend ReadOnly Property SmolExtrasName() As String
            Get
                Return ResourceManager.GetString("SmolExtrasName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remove HUD.
        '''</summary>
        Friend ReadOnly Property SmolExtrasNOHUD() As String
            Get
                Return ResourceManager.GetString("SmolExtrasNOHUD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Soft-Freeze Camera.
        '''</summary>
        Friend ReadOnly Property SoftFreezeCamera() As String
            Get
                Return ResourceManager.GetString("SoftFreezeCamera", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Soft-Unfreeze Camera.
        '''</summary>
        Friend ReadOnly Property SoftUnfreezeCamera() As String
            Get
                Return ResourceManager.GetString("SoftUnfreezeCamera", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Surprise() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Surprise", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tools.
        '''</summary>
        Friend ReadOnly Property ToolsMenu() As String
            Get
                Return ResourceManager.GetString("ToolsMenu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Tutorials() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tutorials", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Undo previous animation swaps.
        '''</summary>
        Friend ReadOnly Property UndoAllPrevSwaps() As String
            Get
                Return ResourceManager.GetString("UndoAllPrevSwaps", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to When you select a new animation to be overwritten, the previous one
        '''will be returned to its default animation..
        '''</summary>
        Friend ReadOnly Property UndoAllPrevSwapsTooltip() As String
            Get
                Return ResourceManager.GetString("UndoAllPrevSwapsTooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unfreeze Camera.
        '''</summary>
        Friend ReadOnly Property UnfreezeCamera() As String
            Get
                Return ResourceManager.GetString("UnfreezeCamera", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property User() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("User", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Vegas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vegas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Vegas10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vegas10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VFX() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VFX", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Yes() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Yes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property YouDontSay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("YouDontSay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property zenonbye() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zenonbye", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
